version: "3"
services:
  frontend:
    build:
      dockerfile: Dockerfile.dev
      context: ./frontend

    volumes:
      - /app/node_modules
      - ./frontend:/app
    stdin_open: true

  nginx:
    restart: always
    build:
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "3000:80"

  backend:
    build:
      dockerfile: Dockerfile.dev
      context: ./backend
    container_name: app_backend
    volumes:
      - /app/node_modules
      - ./backend:/app
#  mysql:
#    build: ./mysql
#    restart: unless-stopped
#    container_name: app_mysql
#    ports:
#      - "3306:3306"
#      # 원래는 컨테이너를 지우면 컨테이너에 저장된 데이터가 지워짐.
#      # 컨테이너에서 변화가 일어난 데이터를 호스트 파일 시스템에 저장하고,
#      # 그 중에서도 도커에 의해서만 통제가 되는 도커 Area에 저장하므로
#      # 컨테이너를 삭제해도 변화된 데이터가 사라지지 않는다.
#    volumes:
#      - ./mysql/mysql_data:/var/lib/mysql
#      - ./mysql/sqls/:/docker-entrypoint-initdb.d/
#    environment:
#      MYSQL_ROOT_PASSWORD: password
#      MYSQL_DATABASE: myapp
